# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='websites'),
        ),
    ]
